### PR TITLE
Add lazy-load attribute to course images

### PR DESCRIPTION
**Pull request by annabelsegalld2l**
See documentation here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading

Course images are mainly used in the MyCourses and course banner selection widgets. In these cases, we load 20 courses at a time, loading 20 images. Adding loading="lazy" to the course image will prevent images from being loaded before they are scrolled to in the widget. In mobile cases (where only 2 images are visible in the viewport) this can lead to a 90% initial download savings (no more need to load the other 18 images until they are scrolled to!).

### CODE REVIEW

**Review by dlockhart — APPROVED** [review]
Awesome! Such a simple way to get some great savings. 🎉

**Review by svanherk — APPROVED** [review]
Nice!  You mentioned it was added to content but turned off because of issues - I'm assuming that's this? https://github.com/Brightspace/lms-launch-darkly-flags/blob/master/features/littlefoot/htmlfilter-lazyload-img.feature.json

**Comment by annabelsegalld2l** [comment]
> Nice! You mentioned it was added to content but turned off because of issues - I'm assuming that's this? https://github.com/Brightspace/lms-launch-darkly-flags/blob/master/features/littlefoot/htmlfilter-lazyload-img.feature.json

Yep, that's it. It looks like the announcements tool is actually using that flag as well (on Spark, I can't see the loading=lazy tag). Here's the defect that turned it off in prod: https://rally1.rallydev.com/#/15545167705d/custom/21568985922?detail=%2Fdefect%2F374915867088.

I was not able to repro this issue with the course images (uploaded my own image, refreshed, seemed to load fine). 
Should we put a feature flag around this? I think it's pretty low risk and could be reverted if any issues arise. Any thoughts?

**Comment by svanherk** [comment]
The defect mentions database files are much more susceptible than content files.  I think the uploaded course images are content files right?  I think they get added to "Manage Files" area of a course, but not sure what type that is

**Comment by annabelsegalld2l** [comment]
> The defect mentions database files are much more susceptible than content files. I think the uploaded course images are content files right? I think they get added to "Manage Files" area of a course, but not sure what type that is

Yes, uploaded images get added to manage files, which are all content files. Database files are things like quizzes, I believe.

**Comment by svanherk** [comment]
Flagging this would be a bit painful, we'd have to pass it down through lots of layers of components.  @klhuff is also working in this space for inspiration to infinitely cache the images themselves, and bust that cache with each upload to lighten the load on the file system.

**Comment by svanherk** [comment]
> (uploaded my own image, refreshed, seemed to load fine)

Also, this is a bug that seems to have been introduced with the new `organizations` route caching.  It used to immediately refresh, whereas now you need to reload with cache disabled or wait for the cache to expire (up to 5 min).  Gonna chat with Chester about options here and then log the defect somewhere

**Pull request merged**
